config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'widgets#listall', as:'home'
  get 'about' => 'pages#about'
  get "users/show" => 'users#new_release1', :as => :new_release1
  get "users/new_release" => 'users#new_release', :as => :new_release
  post "users/login" => 'users#login', :as => :login
  get "users/logout" => 'users#destroy', :as => :logout
  get "users/details" => 'users#details', :as => :userdetails
  get "widgets/search" => 'widgets#search', :as => :searchwidgets
  resources :widgets
  resources :users
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

    def index
        @session = session[:token].nil? ? nil : session[:token]

        token = @session["token"]["access_token"]

        headers = {
          'Content-Type' => 'application/json',
          'Authorization' => "Bearer #{token}" 
        }

        params = {
            "client_id": ENV.fetch('CLIENT_ID'),
            "client_secret": ENV.fetch('CLIENT_SECRET')
        }
        response = ApiCall.new("https://showoff-rails-react-production.herokuapp.com", "get", "/api/v1/users/me/widgets", "", params, headers).execute()
        puts response
        response = JSON.parse(response.body)
        @widgets = response["data"]
    end

    def edit
      @id = params[:id]
    end

    def update
      puts "I am here :)"
    end 
    
    def destroy
      
      @session = session[:token].nil? ? nil : session[:token]
      widget_id = params[:id]
      token = @session["token"]["access_token"]

      headers = {
        'Content-Type' => 'application/json',
        'Authorization' => "Bearer #{token}" 
      }

      response = ApiCall.new("https://showoff-rails-react-production.herokuapp.com", "delete", "/api/v1/widgets/#{widget_id}", "", {}, headers).execute()
      response = JSON.parse(response.body)
      puts response
    end

    def listall
      @session = session[:token].nil? ? nil : session[:token]
      params = {
          "client_id": ENV.fetch('CLIENT_ID'),
          "client_secret": ENV.fetch('CLIENT_SECRET')
      }
      response = ApiCall.new("https://showoff-rails-react-production.herokuapp.com", "get", "/api/v1/widgets/visible", "", params).execute()
      response = JSON.parse(response.body)
      @widgets = response["data"]
    end

    def new
      
    end

    def search
      @searchText = params[:search].split("=").last
      
      params = {
        "client_id": ENV.fetch('CLIENT_ID'),
        "client_secret": ENV.fetch('CLIENT_SECRET'),
        "term": @searchText
      }
      response = ApiCall.new("https://showoff-rails-react-production.herokuapp.com", "get", "/api/v1/widgets/visible", "", params).execute()
      response = JSON.parse(response.body)
      @selected = response["data"]
      @selected = @selected["widgets"]
      
      respond_to do |format|
        format.js
      end
    end

    def create
        #render plain: params[:post].inspect
        if params[:user].nil?
          redirect_to home_path
        end
  
        @session = session[:token].nil? ? nil : session[:token]
        
        token = @session["token"]["access_token"]

        headers = {
          'Content-Type' => 'application/json',
          'Authorization' => "Bearer #{token}" 
        }

        userDetails =  {
          "widget": {
            "name": params[:post]["name"],
            "description": params[:post]["description"],
            "kind": params[:post]["kind"]
          }
        }
  
        response = ApiCall.new("https://showoff-rails-react-production.herokuapp.com", "post", "/api/v1/widgets", userDetails,  {}, headers).execute()
        puts response
    end

    def list
        authorization_object = Authorization.new(request)
        current_user = authorization_object.current_user
        if current_user == Group.find(params[:id]).created_by
          # post message
        else
          # respond: You are not allowed to post to this group
        end
      end

end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_item_grid.html.erb
<table class="table">
<thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">User</th>
    <% if edit == true %>
      <th scope="col">Action</th>
    <% end %>
  </tr>
</thead>
<tbody id="items_grid" class="widget_tbody_content">
  <% if !items.nil? %>
      <%= render partial: 'widgets/items_list', locals: {items: items, edit: edit}  %>
  <% else %>
    <tr>
      <td colspan="4">No Data Found</td>
    <tr>
  <% end %>
</tbody>
</table>

app/views/widgets/_items_list.html.erb
<% if !items.nil? %>
    <% items.each do |item| %>
        <tr>
            <th scope="row"><%= item['id'] %></th>
            <td><%= item['name'] %></td>
            <td><%= item['description'] %></td>
            <td><%= link_to(item['user']['name'], user_path(item['user']['id'])) %></td>
            <% if edit == true %>
                <td>
                    <%= link_to("Edit", edit_widget_path(item['id']), :item => item) %>
                    <%= link_to("Delete", widget_path(item['id']), method: :delete) %>
                </td>
            <% end %>
        </tr>
    <% end %>
<% else %>
    <tr>
        <td>No Data Found!</td>
    </tr>
<% end %>

app/views/widgets/edit.html.erb
<% provide(:title, "Sign in") %>
<h1>Edit Widget</h1>
<%= :item %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for :put, method: :put, url: widgets_path(:id => @id) do |f| %>
      <%= f.text_field(:id, {:value => @id, :class => 'form-control hidden'}) %>

      <%= f.label :name %>
      <%= f.text_field(:name, {:class => 'form-control'}) %>

      <%= f.label :description %>
      <%= f.text_field(:description, {:class => 'form-control'}) %>

      <%= f.label :type %>
      <%= f.text_field(:type, {:class => 'form-control'}) %>
      <br />
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/widgets/index.html.erb
<h1>Users Widgets</h1>
<%= link_to "Create Widgets", new_widget_path %></li>
<%= render partial: 'item_grid', locals: { items: @widgets["widgets"], edit: true} %>

app/views/widgets/index.js.erb
$(".search_widgets").keyup(function() {
    alert("call")
    $.ajax({
       url: '/super_admin/companies/search',
       data: {search: $(this).serialize()}
    });
});

app/views/widgets/listall.html.erb
<h1>Widgets list</h1>
<!-- Search form -->
<%= text_field_tag :search, "", class: "search_widgets form-control", placeholder: "Search" %>
<%= render partial: 'item_grid', locals: { items: @widgets["widgets"], edit: false} %>

<script type="text/javascript">
$(".search_widgets").keyup(function() {
    $.ajax({
       url: '/widgets/search',
       data: {search: $(this).serialize()}
    });
});
</script>

app/views/widgets/new.html.erb
<% provide(:title, "Sign in") %>
<h1>Sign in</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for :post, url: widgets_path do |f| %>

      <%= f.label :email %>
      <%= f.text_field(:email, {:class => 'form-control'}) %>

      <%= f.label :password %>
      <%= f.password_field(:password, {:class => 'form-control'}) %>

      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/widgets/search.js.erb
$("#items_grid").html("<%= escape_javascript(render partial: 'items_list', locals: { items: @selected } ) %>"); 