config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'widgets#listall', as:'home'
  get 'about' => 'pages#about'
  get "users/show" => 'users#new_release1', :as => :new_release1
  get "users/new_release" => 'users#new_release', :as => :new_release
  post "users/login" => 'users#login', :as => :login
  get "users/logout" => 'users#destroy', :as => :logout
  get "users/details" => 'users#details', :as => :userdetails
  get "widgets/search" => 'widgets#search', :as => :searchwidgets
  resources :widgets
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ROR application</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", home_path %></li>
            <% if session[:token] %><li><%= link_to "Widgets", widgets_path %></li><% end %>
            <li><a href="#contact">Users</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if session[:token] %>
                <%= link_to 'Logout', logout_path  %>
              <% else %>
                <%= link_to 'Login', new_release_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <%= render 'users/login' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel"></div>
</html>